language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

services:
  - mysql

before_install:
  - travis_retry composer self-update

before_script:
  - composer self-update
  - composer install
  - php artisan key:generate
  - mysql -e 'create database antvelDB;'

script: vendor/bin/phpunit